name: platformio
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: '[checkout]'
      uses: actions/checkout@v1
    
    - name: '[setup] gitversion'
      uses: gittools/actions/setup-gitversion@v0.3
      with:
          versionSpec: '5.1.x'
    
    - name: '[setup] python'
      uses: actions/setup-python@v1
      with:
          python-version: '3.8'
          architecture: 'x64'
    
    - name: '[setup] platformio'
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio==4.1.0
        platformio update
    
    - id: gitversion
      name: '[prebuild] execute gitversion'
      uses: gittools/actions/execute-gitversion@v0.3
    
    - id: version
      name: '[prebuild] calculate version'
      run: |
        echo ::set-output name=version::${{ steps.gitversion.outputs.semVer }}-${{ steps.gitversion.outputs.shortSha }}

    - name: '[prebuild] apply version'
      run: |
        #sed -i 's/0.0.0/${{ steps.version.outputs.version }}/g' ./src/Device.cpp
        sed -i 's/0.0.0/${{ steps.gitversion.outputs.semVer }}/g' ./src/Device.cpp
    
    - name: '[build] build firmware'
      run: |
        platformio run

    - name: '[postbuild] apply version'
      run: |
        mv .pio/build/esp8266/firmware.elf firmware-${{ steps.version.outputs.version }}.elf
    
    - id: draft
      name: '[release] create draft'
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gitversion.outputs.semVer }}
        release_name: v${{ steps.gitversion.outputs.semVer }}
        draft: true
        prerelease: true
        body: |

    - name: '[release] upload firmware'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.draft.outputs.upload_url }}
        asset_path: firmware-${{ steps.version.outputs.version }}.elf
        asset_name: firmware-${{ steps.version.outputs.version }}.elf
        asset_content_type: application/elf
