name: platformio
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    
    - name: gitversion-setup
      uses: gittools/actions/setup-gitversion@v0.3
      with:
          versionSpec: '5.1.x'
    
    - name: python setup
      uses: actions/setup-python@v1
      with:
          python-version: '3.8'
          architecture: 'x64'
    
    - name: platformio setup
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio==4.1.0
        platformio update
    
    - id: gitversion
      name: gitversion execute
      uses: gittools/actions/execute-gitversion@v0.3
    - name: platformio-build
      run: |
        platformio run
    
    - id: version
      name: gitversion apply
      run: |
        set version=${{ steps.gitversion.outputs.semVer }}-${{ steps.gitversion.outputs.shortSha }}
        echo "::set-output version=${version}"
        sed -i 's/0.0.0/${version}/g' src/Device.cpp
        cd .pio/build/esp8266
        mv firmware.elf firmware-${version}.elf
    
    - id: draft
      name: draft
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gitversion.outputs.semVer }}
        release_name: v${{ steps.gitversion.outputs.semVer }}
        draft: true
        prerelease: true
    
    - name: draft upload asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.draft.outputs.upload_url }}
        asset_path: .pio/build/esp8266/firmware-${{ steps.version.outputs.version }}.elf
        asset_name: firmware-{{ steps.version.outputs.version }}.elf
        asset_content_type: application/elf
