name: platformio
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: gitversion-setup
      uses: gittools/actions/setup-gitversion@v0.3
      with:
          versionSpec: '5.1.x'
    - name: gitversion-execute
      uses: gittools/actions/execute-gitversion@v0.3
      id: gitversion
    - name: platformio-setup
      uses: actions/setup-python@v1
      with:
          python-version: '3.8'
          architecture: 'x64'
    - name: install platformio
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio==4.1.0
        platformio update
    - name: platformio-build
      run: |
        platformio run
    - run: |
        echo "version: ${{ steps.gitversion.outputs.semVer }}-${{ steps.gitversion.outputs.shortSha }}"
